### ISSUE TITLE
Facing a build issue due to errors in api.hpp

### ISSUE THREAD

**Issue by ghost** [absceptual/unity-dumper#1]
![image](https://user-images.githubusercontent.com/121299095/214901663-309707e7-282b-450c-a7ca-48c6ab34b38b.png)
Tried running the `main.cpp` code just for testing but I was facing these errors. Faced the same in Visual Studio IDE too. Can you help me fix these?

**Comment by absceptual** [comment]
You'll need to use **C++17** and higher as inline variables are now supported from that point on.

**Comment by ghost** [comment]
Ah yes it worked ty. Btw is it possible to modify it to make it work for games like Genshin Impact? Just wondering.

**Comment by absceptual** [comment]
I never got around to testing games with obfuscated metadata but either way it should work properly, you may have to search for the obfuscated/deobfuscated names you're looking for. Can't give too much detail as I haven't been pursuing reverse engineering in a while.
